### ISSUE TITLE
Tiny error terms in UDDsketch produce odd results....

### ISSUE THREAD

**Issue by davidkohn88** [timescale/timescale-analytics#115]
**Relevant system information:**
Timescale Forge - PG 12.6 - Timescale Analytics 0.2

**Describe the bug**
Very small values of the error term in the `uddsketch` produce odd results. 

**To Reproduce**
make a uddsketch with an error term small enough and the result will go to 1:
ie:
```SQL
select timescale_analytics_experimental.quantile(timescale_analytics_experimental.uddsketch(100, 0.00000000001, fill_level::double precision ), 0.5) FROM demo.fill_measurements_2h_chunk WHERE time >= '2021-04-10 07:50:00' AND time < '2021-04-10 11:00:00';
``` 
Result = 250.5056... which is close to correct. 
as you add more decimal places the error gets worse from there until:

```SQL
select timescale_analytics_experimental.quantile(timescale_analytics_experimental.uddsketch(100, 0.00000000000000001, fill_level::double precision ), 0.5) FROM demo.fill_measurements_2h_chunk WHERE time >= '2021-04-10 07:50:00' AND time < '2021-04-10 11:00:00';
``` 
where the result is 1, no matter the quantile you ask for.

(Also, the result of 
```SQL
select timescale_analytics_experimental.error(timescale_analytics_experimental.uddsketch(100, 0.00000000000000001, fill_level::double precision )) FROM demo.fill_measurements_2h_chunk WHERE time >= '2021-04-10 07:50:00' AND time < '2021-04-10 11:00:00';
``` 

is 1e-17, which, I believe is the input error term. So it's unclear if it's recognizing the problem, whereas the result of 

```SQL
select timescale_analytics_experimental.error(timescale_analytics_experimental.uddsketch(100, 0.00000000001, fill_level::double precision )) FROM demo.fill_measurements_2h_chunk WHERE time >= '2021-04-10 07:50:00' AND time < '2021-04-10 11:00:00';
```

 is 2.097...e-5, so it seems at least it's modifying the error term there).

**Comment by WireBaron** [comment]
Josh and I continued looking into this this morning and found that around a target error of 1e-17 the gamma parameter for the UddSketch (computed as (1+target_error)/(1-target_error)) becomes 1.0.  Since the bucket for a value is log base gamma of that value, once gamma becomes 1.0 all values get an infinite bucket id and get lumped into the same bucket.

There also appears to be some other odd behavior with ultra low target errors, likely due to loss of precision.  To address this and the above issue, we're planning on restricting the target error to the range [1e-12, 1).

**Comment by davidkohn88** [comment]
I believe this was fixed in: https://github.com/timescale/timescale-analytics/pull/118
